// Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_fonts
export const fontsModule = [
	'font',
	'font-family',
	'font-feature-settings',
	'font-kerning',
	'font-language-override',
	'font-optical-sizing',
	'font-palette',
	'font-size',
	'font-size-adjust',
	'font-stretch',
	'font-style',
	'font-weight',
	'font-synthesis',
	'font-synthesis-small-caps',
	'font-synthesis-style',
	'font-synthesis-weight',
	'font-variant',
	'font-variant-alternates',
	'font-variant-caps',
	'font-variant-east-asian',
	'font-variant-emoji',
	'font-variant-ligatures',
	'font-variant-numeric',
	'font-variant-position',
	'font-variation-settings',
];
