// Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_masking
export const maskingModule = [
	'clip',
	'clip-path',
	'clip-rule',
	'mask',
	'mask-border',
	'mask-border-mode',
	'mask-border-outset',
	'mask-border-repeat',
	'mask-border-slice',
	'mask-border-source',
	'mask-border-width',
	'mask-clip',
	'mask-composite',
	'mask-image',
	'mask-mode',
	'mask-origin',
	'mask-position',
	'mask-repeat',
	'mask-size',
	'mask-type',
];
