// Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scroll_snap
export const scrollSnapModule = [
	'scroll-snap-type',
	'scroll-padding',
	'scroll-padding-top',
	'scroll-padding-right',
	'scroll-padding-bottom',
	'scroll-padding-left',
	'scroll-padding-inline',
	'scroll-padding-inline-start',
	'scroll-padding-inline-end',
	'scroll-padding-block',
	'scroll-padding-block-start',
	'scroll-padding-block-end',
	'scroll-snap-align',
	'scroll-margin',
	'scroll-margin-top',
	'scroll-margin-right',
	'scroll-margin-bottom',
	'scroll-margin-left',
	'scroll-margin-inline',
	'scroll-margin-inline-start',
	'scroll-margin-inline-end',
	'scroll-margin-block',
	'scroll-margin-block-start',
	'scroll-margin-block-end',
	'scroll-snap-stop',
];
