// Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_text
export const textModule = [
	'hanging-punctuation',
	'hyphenate-character',
	'hyphenate-limit-chars',
	'hyphens',
	'letter-spacing',
	'line-break',
	'overflow-wrap',
	'tab-size',
	'text-align',
	'text-align-last',
	'text-indent',
	'text-justify',
	'text-spacing-trim',
	'text-transform',
	'text-wrap',
	'text-wrap-mode',
	'text-wrap-style',
	'white-space',
	'white-space-collapse',
	'word-break',
	'word-spacing',
	'word-wrap',
];
